package com.railway.railwayecsystem.model;

import java.util.Date;

public class DsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.logon_name
     *
     * @mbggenerated
     */
    private String logonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.eff_date
     *
     * @mbggenerated
     */
    private Date effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.exp_date
     *
     * @mbggenerated
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.last_name
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.first_name
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.account_status
     *
     * @mbggenerated
     */
    private Long accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.sex
     *
     * @mbggenerated
     */
    private Long sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.lst_logon_date
     *
     * @mbggenerated
     */
    private Date lstLogonDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.pwd_change_date
     *
     * @mbggenerated
     */
    private Date pwdChangeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.create_userid
     *
     * @mbggenerated
     */
    private Long createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.account_type
     *
     * @mbggenerated
     */
    private Long accountType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.id
     *
     * @return the value of ds_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.id
     *
     * @param id the value for ds_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.logon_name
     *
     * @return the value of ds_user.logon_name
     *
     * @mbggenerated
     */
    public String getLogonName() {
        return logonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.logon_name
     *
     * @param logonName the value for ds_user.logon_name
     *
     * @mbggenerated
     */
    public void setLogonName(String logonName) {
        this.logonName = logonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.eff_date
     *
     * @return the value of ds_user.eff_date
     *
     * @mbggenerated
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.eff_date
     *
     * @param effDate the value for ds_user.eff_date
     *
     * @mbggenerated
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.exp_date
     *
     * @return the value of ds_user.exp_date
     *
     * @mbggenerated
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.exp_date
     *
     * @param expDate the value for ds_user.exp_date
     *
     * @mbggenerated
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.last_name
     *
     * @return the value of ds_user.last_name
     *
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.last_name
     *
     * @param lastName the value for ds_user.last_name
     *
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.first_name
     *
     * @return the value of ds_user.first_name
     *
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.first_name
     *
     * @param firstName the value for ds_user.first_name
     *
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.account_status
     *
     * @return the value of ds_user.account_status
     *
     * @mbggenerated
     */
    public Long getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.account_status
     *
     * @param accountStatus the value for ds_user.account_status
     *
     * @mbggenerated
     */
    public void setAccountStatus(Long accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.sex
     *
     * @return the value of ds_user.sex
     *
     * @mbggenerated
     */
    public Long getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.sex
     *
     * @param sex the value for ds_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Long sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.phone
     *
     * @return the value of ds_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.phone
     *
     * @param phone the value for ds_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.email
     *
     * @return the value of ds_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.email
     *
     * @param email the value for ds_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.lst_logon_date
     *
     * @return the value of ds_user.lst_logon_date
     *
     * @mbggenerated
     */
    public Date getLstLogonDate() {
        return lstLogonDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.lst_logon_date
     *
     * @param lstLogonDate the value for ds_user.lst_logon_date
     *
     * @mbggenerated
     */
    public void setLstLogonDate(Date lstLogonDate) {
        this.lstLogonDate = lstLogonDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.pwd_change_date
     *
     * @return the value of ds_user.pwd_change_date
     *
     * @mbggenerated
     */
    public Date getPwdChangeDate() {
        return pwdChangeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.pwd_change_date
     *
     * @param pwdChangeDate the value for ds_user.pwd_change_date
     *
     * @mbggenerated
     */
    public void setPwdChangeDate(Date pwdChangeDate) {
        this.pwdChangeDate = pwdChangeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.password
     *
     * @return the value of ds_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.password
     *
     * @param password the value for ds_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.status
     *
     * @return the value of ds_user.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.status
     *
     * @param status the value for ds_user.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.create_date
     *
     * @return the value of ds_user.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.create_date
     *
     * @param createDate the value for ds_user.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.update_time
     *
     * @return the value of ds_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.update_time
     *
     * @param updateTime the value for ds_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.create_userid
     *
     * @return the value of ds_user.create_userid
     *
     * @mbggenerated
     */
    public Long getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.create_userid
     *
     * @param createUserid the value for ds_user.create_userid
     *
     * @mbggenerated
     */
    public void setCreateUserid(Long createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_user.account_type
     *
     * @return the value of ds_user.account_type
     *
     * @mbggenerated
     */
    public Long getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_user.account_type
     *
     * @param accountType the value for ds_user.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(Long accountType) {
        this.accountType = accountType;
    }
}