package com.railway.railwayecsystem.mapper;

import com.railway.railwayecsystem.model.DsUser;

import javax.annotation.Resource;
import java.util.List;
@Resource(name="dsUserMapper")
public interface DsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_user
     *
     * @mbggenerated
     */
    int insert(DsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_user
     *
     * @mbggenerated
     */
    int insertSelective(DsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_user
     *
     * @mbggenerated
     */
    DsUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DsUser record);

	List<DsUser> selectUsers();
}